version: "3.8"
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    working_dir: /usr/src/app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app/src
    environment:
      - DATABASE_HOSTNAME=hostname
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=database_name
      - DATABASE_USERNAME=root
      - SECRET_KEY=somesecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUGGING=1
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
