version: "3"
services:
  api:
    working_dir: /usr/src/app/src
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app
    # env_file:
    #     - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=hostname
    #   - DATABASE_PORT=5432
    #   - DATABASE_PASSWORD=password123
    #   - DATABASE_NAME=database_name
    #   - DATABASE_USERNAME=postgres
    #   - SECRET_KEY=somesecretkey
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql
#     environment:
#       - POSTGRES_PASSWORD=password123
#       - POSTGRES_DB=fastapi
#     volumes:
#       - mysql-db:/var/lib/mysqlql/data

# volumes:
#   mysql-db: