version: "3"
services:
  api:
    # working_dir: /src
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app
    # env_file:
    #     - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=hostname
    #   - DATABASE_PORT=5432
    #   - DATABASE_PASSWORD=password123
    #   - DATABASE_NAME=database_name
    #   - DATABASE_USERNAME=postgres
    #   - SECRET_KEY=somesecretkey
    #   - ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: cd src && uvicorn app:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=password123
#       - POSTGRES_DB=fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db: